/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Setting as Setting1, TextboxSetting } from "./components/my-component";
import { Setting } from "./components/my-component";
export namespace Components {
    interface LqL {
        "textbox": TextboxSetting;
    }
    interface MyComponent {
        "setting": Setting;
    }
    interface MyPopup {
        "setting": Setting1;
    }
}
declare global {
    interface HTMLLqLElement extends Components.LqL, HTMLStencilElement {
    }
    var HTMLLqLElement: {
        prototype: HTMLLqLElement;
        new (): HTMLLqLElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyPopupElement extends Components.MyPopup, HTMLStencilElement {
    }
    var HTMLMyPopupElement: {
        prototype: HTMLMyPopupElement;
        new (): HTMLMyPopupElement;
    };
    interface HTMLElementTagNameMap {
        "lq-l": HTMLLqLElement;
        "my-component": HTMLMyComponentElement;
        "my-popup": HTMLMyPopupElement;
    }
}
declare namespace LocalJSX {
    interface LqL {
        "textbox"?: TextboxSetting;
    }
    interface MyComponent {
        "setting"?: Setting;
    }
    interface MyPopup {
        "setting"?: Setting1;
    }
    interface IntrinsicElements {
        "lq-l": LqL;
        "my-component": MyComponent;
        "my-popup": MyPopup;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lq-l": LocalJSX.LqL & JSXBase.HTMLAttributes<HTMLLqLElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-popup": LocalJSX.MyPopup & JSXBase.HTMLAttributes<HTMLMyPopupElement>;
        }
    }
}
